### ISSUE TITLE
Field values based on values of other field

### ISSUE THREAD

**Issue by MKstudio-Tech** [snapcrunch/electron-preferences#173] opened 2022-07-19 14:46 UTC
Example: I have a dropdown menu where  i want to have values of a list field as options to choose.

**Comment by lacymorrow** [comment] 2022-07-19 19:04
Yep, this is a huge one for me as well, I just haven't had much free time but had thought of implementing it myself.

This is a duplicate of #160]

**Closed by lacymorrow** 2022-07-19 19:04 UTC
Labels: enhancement
